### ISSUE TITLE
MSSQL service latest version no longer supported

### ISSUE THREAD

**Issue by sdunham** [lando/cli#12]
It looks like the `mssql` service is configured to use the `latest` tag as the default version. Unfortunately it looks like a recent update removed the `latest` tag as an option on DockerHub, which means that building a `mssql` service with the default configuration results in an error pulling down the docker container. It looks like the closest alternative to the `latest` tag is `2019-latest`.

Additionally, the docker image being used by lando for the `mssql` service (`microsoft/mssql-server-linux`) has been deprecated in favor of `mcr.microsoft.com/mssql/server`, so I'm assuming this should be updated as well.

If I could get some guidance on which version(s) you'd like to support and if there are any concerns switching the image, I think I could knock out a PR for this fairly quickly using the `mysql` service as a reference. Here's a link to the new docker image: https://hub.docker.com/_/microsoft-mssql-server

To anyone who happens upon this before the issue has been resolved, here's how to work around this issue via custom configuration for your service:

```
my-database-service:
    # Use custom version
    type: mssql:custom
    overrides:
      # Override the image name and use the version 2019-latest
      image: 'mcr.microsoft.com/mssql/server:2019-latest'
```
