### ISSUE TITLE
How can the default path of lando ssh be changed?

### ISSUE THREAD

**Issue by ayalon** [lando/cli#207]
I have a custom mount for my image. 
```
    type: node:18
    app_mount: false
    overrides:
      volumes:
        - "./frontend:/nuxt"
```

This works but when I do `lando ssh` I'm always at `/app` which is empty.
How can I tell lando to go to `/nuxt` when I login?

**Comment by reynoldsalec** [comment]
I don't think this is possible in Lando v3, but I do know that having a configurable app root is part of Lando v4's spec.

**Comment by AaronFeledy** [comment]
As a workaround you could make your own alternate tooling command that does this. Something like this:
```
services:
  front:
    type: node:18
    app_mount: false
    overrides:
      volumes:
        - "./frontend:/nuxt"

tooling:
  ssh-front:
    service: frontend
    cmd: bash
    dir: /nuxt
```
