### ISSUE TITLE
Specify services/tooling via "lando init"

### ISSUE THREAD

**Issue by klonos** [lando/cli#210]
I've already read https://docs.lando.dev/basics/init.html and know that I can for example do this:

```bash
lando init \
  --source remote \
  --remote-url https://github.com/drupal/drupal.git \
  --remote-options="--branch 8.9.x --depth 1" \
  --recipe drupal8 \
  --webroot ./docroot \
  --name d8test \
  --option composer_version=2.0.7 \
  --option database=mariadb
```

Which results in this:

```yaml
name: d8test
recipe: drupal8
config:
  webroot: ./docroot
  composer_version: 2.0.7
  database: mariadb
```

Can `lando init` accept parameters for setting other things, like `services` and `tooling`? For example, I would like to end up with:

```yaml
name: d8test
recipe: drupal8
config:
  webroot: ./docroot
  composer_version: 2.0.7
  database: mariadb

services:
  appserver:
    extras:
      - bla bla
      - bla bla bla
  phpmyadmin:
    type: phpmyadmin
    hosts: database

tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/docroot --uri=http://d8test.lndo.site
```
